(with-eval-after-load "custom"
  (load-theme 'base16-twilight-dark t)
  (let ((base00 "#1e1e1e") (base01 "#323537")
        (base02 "#464b50") (base03 "#5f5a60")
        (base04 "#838184") (base05 "#a7a7a7")
        (base06 "#c3c3c3") (base07 "#ffffff")
        (base08 "#cf6a4c") (base09 "#cda869")
        (base0A "#f9ee98") (base0B "#8f9d6a")
        (base0C "#afc4db") (base0D "#7587a6")
        (base0E "#9b859d") (base0F "#9b703f"))
    (custom-set-faces
     `(mode-line ((t (:background ,base01))))
     `(fringe ((t (:background nil :foreground ,base03))))
     `(linum ((t (:background nil))))
     `(vertical-border ((t (:foreground ,base02))))
     `(eshell-ls-directory ((t (:foreground ,base0C))))
     `(eshell-ls-readonly ((t (:foreground ,base05))))
     `(eshell-ls-product ((t (:foreground ,base05))))
     `(eshell-ls-unreadable ((t (:foreground ,base05))))
     `(eshell-ls-backup ((t (:foreground ,base05))))
     `(eshell-ls-archive ((t (:foreground ,base05))))
     `(eshell-ls-clutter ((t (:foreground ,base05))))
     `(eshell-ls-missing ((t (:foreground ,base05))))
     `(eshell-ls-symlink ((t (:foreground ,base0E))))
     `(eshell-ls-executable ((t (:foreground ,base08))))
     `(eshell-ls-special ((t (:foreground ,base0B))))
     `(anzu-mode-line ((t (:foreground ,base0E))))
     `(idle-highlight ((t (:background ,base01))))
     `(company-tooltip ((t (:inherit highlight))))
     `(company-tooltip-selection ((t (:inherit match))))
     `(company-tooltip-common ((t (:inherit company-tooltip :weight bold))))
     `(company-tooltip-common-selection ((t (:inherit company-tooltip-selection :weight bold))))
     `(company-echo ((t (:inherit minibuffer-prompt))))
     `(company-echo-common ((t (:inherit minibuffer-noticeable-prompt))))
     `(company-preview ((t (:inherit primary-selection))))
     `(company-preview-common ((t (:inherit company-preview :weight bold))))
     `(company-preview-search ((t (:inherit secondary-selection))))
     `(company-scrollbar-fg ((t (:inherit region))))
     `(company-scrollbar-bg ((t (:inherit company-tooltip)))))))
